apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sqldb.fullnameOverride }}-secret
  labels:
    {{- include "sqldb.labels" . | nindent 4 }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.pwd.value }}
  edgesql-password: {{ .Values.pwd.value }}
  edgesql-username: sa
  edgesql-hostname: {{ .Values.sqldb.fullnameOverride }}-service