apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: infrastructure
  labels:
    app: zipkin
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 9411
  selector:
    app: zipkin
