---
# Source: temp/templates/values.yaml
image:
  registry: docker.io
  repository: bitnami/elasticsearch
  tag: 8.5.0-debian-11-r0
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/elasticsearch-exporter
    tag: 1.5.0-debian-11-r34
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9114"
    prometheus.io/scrape: "true"
sysctlImage:
  registry: docker.io
  repository: bitnami/bitnami-shell
  tag: 11-debian-11-r47
