apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: "14.11.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: infrastructure
  install:
    remediation:
      retries: 50
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
