apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  chart:
    spec:
      chart: sealed-secrets
      version: "2.7.2"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: infrastructure
  interval: 1m
  releaseName: sealed-secrets-controller
  targetNamespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
