apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluentbit
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: fluent-bit
      version: "0.20.8"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: infrastructure
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
