apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: base
      version: "1.15.3"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: infrastructure
