apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway-config
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: ./applications/coral-system/ManifestDeployments/istio/charts/
      version: "1.0.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
