apiVersion: v1
kind: Service
metadata:
  name: {{coral.app}}
  namespace: {{coral.workspace}}-{{coral.app}}-{{coral.deployment}}
spec:
  selector:
    app: {{coral.app}}
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{port}}
