apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "6.48.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: infrastructure
  install:
    remediation:
      retries: 50
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
