apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{coral.app}}-deployment
  namespace: {{coral.workspace}}-{{coral.app}}-{{coral.deployment}}
  labels:
  {{#coral.labels}}
    {{key}}: {{value}}
  {{/coral.labels}}
spec:
  replicas: {{replicas}}
  selector:
    matchLabels:
      app: {{coral.app}}
  template:
    metadata:
      labels:
        {{#coral.labels}}
        {{key}}: {{value}}
        {{/coral.labels}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{metricsEndpoint}}
        prometheus.io/port: "{{port}}"       
    spec:
      containers:
      - name: {{coral.app}}
        image: {{image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{port}}
        resources:
          limits:
            cpu: {{cpu}}
            memory: {{memory}}
        readinessProbe:
          httpGet:
            path: {{healthEndpoint}}
            port: {{port}}
          initialDelaySeconds: 10
          periodSeconds: 10
