---
# Source: temp/templates/release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-sql-edge
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: ./applications/coral-system/ManifestDeployments/azure-sql-edge/charts
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system