apiVersion: v1
kind: Secret
metadata:
  name: {{name}}-azure-secret
  namespace: {{coral.workspace}}-{{coral.app}}
type: Opaque
data:
  azurestorageaccountkey: dXV1cWJ2cGJ0c3FnSlMwQ3FqOVhhTTdyMmdVVXZYZ3ZudHFmcFYrdnhodk1CT3o4cGZqcEh2OG82dFJZZUVMditFQzY1Z2s4RWlITCtBU3RjcDBKamc9PQ==
  azurestorageaccountname: c3RudHdrb2JzdmRldnc1aHBp

