apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{name}}-pvc
  namespace: {{coral.workspace}}-{{coral.app}}
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  volumeName: {{name}}-pv
  resources:
    requests:
      storage: 100Gi
