apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{name}}-pvc
  namespace: {{coral.workspace}}-{{coral.app}}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
