apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{coral.app}}
  namespace: {{coral.workspace}}-{{coral.app}}
spec:
  hosts:
    - {{versionIndependentName}}
  http:
  - route:
    - destination:
        host: {{versionIndependentName}}
        subset: "{{currentVersion}}"
      weight: {{currentWeight}}
    - destination:
        host: {{versionIndependentName}}
        subset: "{{version}}"
      weight: {{weight}}
