apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: elasticsearch
      version: "19.4.0"
      sourceRef:
        kind: HelmRepository
        name: elasticsearch
        namespace: infrastructure
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
