apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: kiali-operator
      version: "1.58.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: infrastructure
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
