apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: infrastructure
spec:
  values:
    elasticsearch:
      hosts:
        - elasticsearch.infrastructure.svc.cluster.local
      port: 9200
