apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sqldb.fullnameOverride }}-service
  labels:
    {{- include "sqldb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sqldb.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.sqldb.service.port }}
      targetPort: {{ .Values.sqldb.service.port }}
      name: sql
  selector:
    {{- include "sqldb.selectorLabels" . | nindent 4 }}