apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: kibana
      version: "10.2.2"
      sourceRef:
        kind: HelmRepository
        name: kibana
        namespace: infrastructure
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
