apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: infrastructure
spec:
  interval: 1m
  chart:
    spec:
      chart: rabbitmq
      version: "10.3.5"
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: infrastructure
  dependsOn:
    - name: istio-base
    - name: istiod
    - name: istio-gateway
